// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messagemock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/t5mx27dp/wsapp/message"
)

// NewMessage creates a new instance of Message. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Message {
	mock := &Message{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

type Message_Expecter struct {
	mock *mock.Mock
}

func (_m *Message) EXPECT() *Message_Expecter {
	return &Message_Expecter{mock: &_m.Mock}
}

// GetBody provides a mock function for the type Message
func (_mock *Message) GetBody() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// Message_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type Message_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *Message_Expecter) GetBody() *Message_GetBody_Call {
	return &Message_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *Message_GetBody_Call) Run(run func()) *Message_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Message_GetBody_Call) Return(bytes []byte) *Message_GetBody_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *Message_GetBody_Call) RunAndReturn(run func() []byte) *Message_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function for the type Message
func (_mock *Message) GetType() message.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 message.Type
	if returnFunc, ok := ret.Get(0).(func() message.Type); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(message.Type)
	}
	return r0
}

// Message_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type Message_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *Message_Expecter) GetType() *Message_GetType_Call {
	return &Message_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *Message_GetType_Call) Run(run func()) *Message_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Message_GetType_Call) Return(typeParam message.Type) *Message_GetType_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *Message_GetType_Call) RunAndReturn(run func() message.Type) *Message_GetType_Call {
	_c.Call.Return(run)
	return _c
}
